Repository ros-navigation/navigation2, pull requests merged in 2018-11, with the labels that each got.

#291 AMCL: Enabling dynamic reconfigure #209
  nav2_amcl/CMakeLists.txt
  nav2_amcl/package.xml
  nav2_amcl/src/amcl_node.cpp
  nav2_amcl/src/amcl_node.hpp
Labels: 1 - High, enhancement

#292 Cleaned amcl_node header file
  nav2_amcl/src/amcl_node.hpp
Labels: 2 - Medium, nav2_localization

#311 Task server not node
  nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
  nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
  nav2_mission_executor/include/nav2_mission_executor/mission_executor.hpp
  nav2_mission_executor/src/mission_executor.cpp
  nav2_robot/include/nav2_robot/robot.hpp
  nav2_robot/src/robot.cpp
  nav2_robot/test/test_robot_class.cpp
  nav2_simple_navigator/include/nav2_simple_navigator/simple_navigator.hpp
  nav2_simple_navigator/src/simple_navigator.cpp
  nav2_smart_planner/include/nav2_smart_planner/navfn.hpp
  nav2_smart_planner/include/nav2_smart_planner/smart_planner.hpp
  nav2_smart_planner/src/smart_planner.cpp
  nav2_tasks/include/nav2_tasks/costmap_service_client.hpp
  nav2_tasks/include/nav2_tasks/task_client.hpp
  nav2_tasks/include/nav2_tasks/task_server.hpp
  nav2_tasks/test/test_tasks.cpp
Labels: 1 - High

#307 Fix costmap publishing loop
  nav2_costmap_2d/src/costmap_2d_publisher.cpp
  nav2_costmap_2d/src/costmap_2d_ros.cpp
  nav2_util/CMakeLists.txt
  nav2_util/include/nav2_util/execution_timer.hpp
  nav2_util/test/CMakeLists.txt
  nav2_util/test/test_execution_timer.cpp
Labels: 1 - High

#320 Fixing last_publish_ time to be RCL_ROS_TIME by default.
  nav2_costmap_2d/src/costmap_2d_ros.cpp
Labels: 0 - Critical

#321 Replace manual layered costmap with costmap2dROS object
  nav2_world_model/include/nav2_world_model/world_model.hpp
  nav2_world_model/src/main.cpp
  nav2_world_model/src/world_model.cpp
Labels: 1 - High

#322 Voxel Layer Port
  nav2_costmap_2d/CMakeLists.txt
  nav2_costmap_2d/include/nav2_costmap_2d/voxel_layer.hpp
  nav2_costmap_2d/package.xml
  nav2_costmap_2d/plugins/voxel_layer.cpp
  nav2_msgs/CMakeLists.txt
  nav2_msgs/msg/VoxelGrid.msg
  nav2_voxel_grid/CMakeLists.txt
  nav2_voxel_grid/include/nav2_voxel_grid/voxel_grid.hpp
  nav2_voxel_grid/src/voxel_grid.cpp
  nav2_voxel_grid/test/voxel_grid_tests.cpp
Labels: 2 - Medium

#323 Planner hook fix
  nav2_smart_planner/include/nav2_smart_planner/smart_planner.hpp
  nav2_smart_planner/src/smart_planner.cpp
Labels: 1 - High

#343 Add angles back to ros2_dependencies to fix master build
  tools/ros2_dependencies.repos
Labels: 0 - Critical

#329 fixing costmap_2d_ros logic operator bug
  nav2_costmap_2d/src/costmap_2d_ros.cpp
Labels: bug, costmap_2d

#336 Fix robot class to use cmd_vel topic
  nav2_robot/src/robot.cpp
Labels: 1 - High, bug

#324 Enable colcon-test in travis for passing packages
  .travis.yml
Labels: 1 - High

#342 Fix loading of stopped goal checker.
  nav2_dwb_controller/dwb_plugins/CMakeLists.txt
Labels: 0 - Critical

#332 Smart to navfn
  .travis.yml
  doc/design/ROS_COMPARISON.md
  nav2_bringup/launch/core.launch.py
  nav2_bringup/launch/nav2_bringup_launch.py
  nav2_navfn_planner/CHANGELOG.rst
  nav2_navfn_planner/CMakeLists.txt
  nav2_navfn_planner/README.md
  nav2_navfn_planner/include/nav2_navfn_planner/navfn.hpp
  nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
  nav2_navfn_planner/package.xml
  nav2_navfn_planner/src/main.cpp
  nav2_navfn_planner/src/navfn.cpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_navfn_planner/test/.gitignore
  nav2_system_tests/src/planning/test_planner_launch.py
  navigation2/package.xml
Labels: 1 - High
