Repository ros-navigation/navigation2, pull requests merged in 2018-12, with the labels that each got.

#351 Update nav2_bringup readme for robot
  nav2_bringup/README.md
  nav2_bringup/launch/nav2_bringup_1st_launch.py
  nav2_bringup/launch/nav2_bringup_2nd_launch.py
Labels: 1 - High

#265 Map server params update and refactoring
  nav2_bringup/launch/nav2_bringup_launch.py
  nav2_bringup/launch/nav2_params.yaml
  nav2_bringup/launch/test_map.yaml
  nav2_map_server/CMakeLists.txt
  nav2_map_server/README.md
  nav2_map_server/include/nav2_map_server/base_map_server.hpp
  nav2_map_server/include/nav2_map_server/map_factory.hpp
  nav2_map_server/include/nav2_map_server/map_loader.hpp
  nav2_map_server/include/nav2_map_server/map_representations/map_reps.hpp
  nav2_map_server/include/nav2_map_server/map_representations/occ_grid_server.hpp
  nav2_map_server/include/nav2_map_server/map_server.hpp
  nav2_map_server/include/nav2_map_server/occ_grid_loader.hpp
  nav2_map_server/package.xml
  nav2_map_server/src/main.cpp
  nav2_map_server/src/map_representations/map_factory.cpp
  nav2_map_server/src/map_representations/occ_grid_server.cpp
  nav2_map_server/src/map_server.cpp
  nav2_map_server/src/map_server_ros.cpp
  nav2_map_server/src/occ_grid_loader.cpp
  nav2_map_server/test/component/test_occ_grid_launch.py
  nav2_map_server/test/component/test_occ_grid_node.cpp
  nav2_map_server/test/map_server_params.yaml
  nav2_map_server/test/test_constants.cpp
  nav2_map_server/test/test_constants/test_constants.h
  nav2_map_server/test/test_launch_files/map_server_node.launch.py
  nav2_map_server/test/testmap.yaml
  nav2_map_server/test/unit/test_occ_grid.cpp
Labels: 1 - High

#458 Getting Build Farm CI on track
  nav2_amcl/CMakeLists.txt
  nav2_amcl/package.xml
  nav2_bringup/CMakeLists.txt
  nav2_bringup/package.xml
  nav2_bt_navigator/package.xml
  nav2_costmap_2d/CMakeLists.txt
  nav2_costmap_2d/package.xml
  nav2_costmap_2d/test/footprint_tests.cpp
  nav2_dwb_controller/costmap_queue/package.xml
  nav2_dwb_controller/dwb_controller/CMakeLists.txt
  nav2_dwb_controller/dwb_controller/package.xml
  nav2_dwb_controller/dwb_core/CMakeLists.txt
  nav2_dwb_controller/dwb_core/package.xml
  nav2_dwb_controller/dwb_critics/CMakeLists.txt
  nav2_dwb_controller/dwb_critics/package.xml
  nav2_dwb_controller/dwb_msgs/CMakeLists.txt
  nav2_dwb_controller/dwb_msgs/package.xml
  nav2_dwb_controller/dwb_plugins/CMakeLists.txt
  nav2_dwb_controller/dwb_plugins/package.xml
  nav2_dwb_controller/nav2_dwb_controller/package.xml
  nav2_dwb_controller/nav_2d_msgs/package.xml
  nav2_dwb_controller/nav_2d_utils/package.xml
  nav2_dynamic_params/package.xml
  nav2_map_server/CMakeLists.txt
  nav2_map_server/package.xml
  nav2_map_server/test/component/test_occ_grid_node.cpp
  nav2_mission_executor/CMakeLists.txt
  nav2_mission_executor/package.xml
  nav2_motion_primitives/CMakeLists.txt
  nav2_motion_primitives/package.xml
  nav2_msgs/package.xml
  nav2_navfn_planner/CMakeLists.txt
  nav2_navfn_planner/package.xml
  nav2_robot/package.xml
  nav2_robot/test/test_robot_class.cpp
  nav2_simple_navigator/package.xml
  nav2_system_tests/CMakeLists.txt
  nav2_system_tests/package.xml
  nav2_tasks/CMakeLists.txt
  nav2_tasks/package.xml
  nav2_util/CMakeLists.txt
  nav2_util/package.xml
  nav2_voxel_grid/package.xml
  nav2_world_model/CMakeLists.txt
  nav2_world_model/package.xml
  navigation2/package.xml
  tools/ros2_dependencies.repos
Labels: 0 - Critical

#440 Enable Dynamic Reconfigure of DWB Kinematic Params
  nav2_dwb_controller/dwb_plugins/CMakeLists.txt
  nav2_dwb_controller/dwb_plugins/include/dwb_plugins/kinematic_parameters.hpp
  nav2_dwb_controller/dwb_plugins/package.xml
  nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
  nav2_dwb_controller/dwb_plugins/test/CMakeLists.txt
  nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
Labels: 1 - High

#460 Simplifying is_stuck condition detection
  nav2_tasks/CMakeLists.txt
  nav2_tasks/include/nav2_tasks/is_stuck_condition.hpp
  nav2_tasks/package.xml
Labels: 0 - Critical, nav2_tasks

#475 Fix Travis build - remove gazebo_ros_pkgs dependency
  nav2_system_tests/CMakeLists.txt
  nav2_system_tests/package.xml
  tools/ros2_dependencies.repos
Labels: 0 - Critical

#478 Remove unneeded depends from nav2_bringup
  nav2_bringup/CMakeLists.txt
  nav2_bringup/package.xml
Labels: 2 - Medium

#465 Refactor map saver
  nav2_map_server/CMakeLists.txt
  nav2_map_server/include/nav2_map_server/map_generator.hpp
  nav2_map_server/src/map_generator.cpp
  nav2_map_server/src/map_saver.cpp
Labels: 2 - Medium

#454 Enabling global planner tester
  nav2_system_tests/CMakeLists.txt
  nav2_system_tests/src/planning/CMakeLists.txt
  nav2_system_tests/src/planning/planner_tester.cpp
  nav2_system_tests/src/planning/planner_tester.hpp
  nav2_system_tests/src/planning/test_planner_node.cpp
  nav2_util/src/costmap.cpp
Labels: 2 - Medium, nav2_system_tests

#493 Robot velocity should be set to zero after primitive is cancelled
  nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
Labels: 1 - High, nav2_motion_primitives

#495 Adjusted path endpoint markers size and duration
  nav2_navfn_planner/src/navfn_planner.cpp
Labels: 3 - Low, nav2_planner

#471 Renaming getCurrentVelocity and getCurrentPose to address #163
  .travis.yml
  nav2_robot/include/nav2_robot/robot.hpp
  nav2_robot/src/robot.cpp
  nav2_robot/test/test_robot_class.cpp
Labels: 2 - Medium

#504 Amcl auto localization
  nav2_bt_navigator/CMakeLists.txt
  nav2_bt_navigator/behavior_trees/auto_localization.xml
  nav2_bt_navigator/behavior_trees/auto_localization_w_parallel_recovery.xml
  nav2_bt_navigator/include/nav2_bt_navigator/navigate_to_pose_behavior_tree.hpp
  nav2_bt_navigator/package.xml
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
  nav2_robot/src/robot.cpp
  nav2_tasks/CMakeLists.txt
  nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp
  nav2_tasks/include/nav2_tasks/is_localized_condition.hpp
  nav2_tasks/include/nav2_tasks/navigate_to_pose_task.hpp
  nav2_tasks/package.xml
Labels: 1 - High
