Repository ros-navigation/navigation2, pull requests merged in 2019-12, with the labels that each got.

#1411 Fix launching multiple gzclient instances
  nav2_bringup/bringup/launch/nav2_multi_tb3_simulation_launch.py
  nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py
Labels: 1 - High

#1418 Fix docs_publish error if nothing to commit.
  sphinx_doc/Makefile
Labels: CI

#1427 Fix build error
  nav2_controller/src/nav2_controller.cpp
  nav2_waypoint_follower/src/waypoint_follower.cpp
Labels: 0 - Critical

#1428 convert navigation2 tutorials to rst format for github pages
  sphinx_doc/howtos/index.rst
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_on_real_Turtlebot3/rviz_after_launch_view.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_on_real_Turtlebot3/rviz_robot_navigating.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_on_real_Turtlebot3/rviz_send_goal.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_on_real_Turtlebot3/rviz_set_initial_pose.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_on_real_Turtlebot3/rviz_slam_map_view.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/gazebo_robot_reached_goal.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/gazebo_turlebot3.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/navigation_with_recovery_behaviours.gif
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_initial_view.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_robot_navigating.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_send_goal_pose.png
  sphinx_doc/howtos/tutorials/docs/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_set_initial_pose.png
  sphinx_doc/howtos/tutorials/docs/navigation2_on_real_turtlebot3.rst
  sphinx_doc/howtos/tutorials/docs/navigation2_with_turtlebot3_in_gazebo.rst
  sphinx_doc/howtos/tutorials/index.rst
Labels: documentation

#1412 fix for #1363 - use clearMap instead of reset to clear costmaps
  nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp
  nav2_costmap_2d/include/nav2_costmap_2d/layer.hpp
  nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
  nav2_costmap_2d/plugins/obstacle_layer.cpp
  nav2_costmap_2d/plugins/static_layer.cpp
  nav2_costmap_2d/plugins/voxel_layer.cpp
  nav2_costmap_2d/src/costmap_2d_ros.cpp
  nav2_costmap_2d/test/integration/obstacle_tests.cpp
Labels: 1 - High
