Repository ros-navigation/navigation2, pull requests merged in 2019-11, with the labels that each got.

#1348 Clean shutdown of system tests
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_lifecycle_manager/src/lifecycle_manager.cpp
  nav2_system_tests/src/system/tester_node.py
Labels: 1 - High

#1249 Turtlebot 3 Waffle Gazebo model with ROS2 depth camera plugin
  nav2_system_tests/models/turtlebot3_waffle_depth_camera/turtlebot3_waffle_realsense/model.config
  nav2_system_tests/models/turtlebot3_waffle_depth_camera/turtlebot3_waffle_realsense/model.sdf
  nav2_system_tests/urdf/turtlebot3_waffle.urdf
Labels: 1 - High, for review

#1349 Execute gzclient and gzserver independently and use the argument 'headless'
  nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py
Labels: for review, nav2_bringup
