Repository ros-navigation/navigation2, pull requests merged in 2019-03, with the labels that each got.

#585 Motion Primitives Readme
  nav2_motion_primitives/README.md
Labels: 2 - Medium

#579 Add service to fully clear costmap
  nav2_costmap_2d/include/nav2_costmap_2d/clear_costmap_service.hpp
  nav2_costmap_2d/plugins/static_layer.cpp
  nav2_costmap_2d/src/clear_costmap_service.cpp
  nav2_msgs/CMakeLists.txt
  nav2_msgs/package.xml
  nav2_msgs/srv/ClearEntireCostmap.srv
Labels: 2 - Medium, enhancement

#590 Motion primitives unit tests
  nav2_motion_primitives/CMakeLists.txt
  nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
  nav2_motion_primitives/test/.gitignore
  nav2_motion_primitives/test/CMakeLists.txt
  nav2_motion_primitives/test/test_motion_primitives.cpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_system_tests/src/dummy_controller/dummy_controller.cpp
  nav2_system_tests/src/dummy_planner/dummy_planner.cpp
  nav2_tasks/include/nav2_tasks/task_server.hpp
Labels: 2 - Medium

#587 Improvements to Global Planner testing
  nav2_system_tests/CMakeLists.txt
  nav2_system_tests/src/planning/planner_tester.cpp
  nav2_system_tests/src/planning/planner_tester.hpp
  nav2_system_tests/src/planning/test_planner_node.cpp
Labels: 2 - Medium, enhancement

#619 Add last pose to DWB trajectory
  nav2_dwb_controller/dwb_plugins/src/limited_accel_generator.cpp
  nav2_dwb_controller/dwb_plugins/src/standard_traj_generator.cpp
  nav2_dwb_controller/dwb_plugins/test/twist_gen.cpp
Labels: dwb_upstream

#620 Change DWB trajectories displayed in RViz to be on the red-green spectrum instead.
  nav2_dwb_controller/dwb_core/src/publisher.cpp
Labels: dwb_upstream

#621 Rotate to goal fixes
  nav2_dwb_controller/dwb_critics/src/rotate_to_goal.cpp
Labels: dwb_upstream
