Repository ros-navigation/navigation2, pull requests merged in 2019-07, with the labels that each got.

#917 Check goal handle status before canceling
  nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
Labels: 1 - High

#918 Fixing bugs with action cancellations
  nav2_bringup/launch/nav2_bringup_launch.py
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
  nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_util/include/nav2_util/simple_action_server.hpp
  nav2_util/test/test_actions.cpp
Labels: 1 - High

#919 nav2 rviz plugin action server timeout fix
  nav2_rviz_plugins/src/navigation_dialog.cpp
Labels: 1 - High, for review

#706 catch exceptions by reference and print relevent information
  nav2_amcl/src/amcl_node.cpp
  nav2_map_server/src/occ_grid_loader.cpp
Labels: 2 - Medium

#947 Fixed a bug to be able to reset recovery node internal states
  nav2_bt_navigator/include/nav2_bt_navigator/recovery_node.hpp
  nav2_bt_navigator/src/recovery_node.cpp
Labels: 1 - High

#924 Build scripts update for ROS2 Dashing
  tools/build_all.sh
  tools/initial_ros_setup.sh
Labels: 3 - Low, for review

#937 Nav2-rviz-plugin changes.
  nav2_rviz_plugins/include/nav2_rviz_plugins/navigation_dialog.hpp
  nav2_rviz_plugins/src/goal_tool.cpp
  nav2_rviz_plugins/src/navigation_dialog.cpp
Labels: 1 - High, for review
