Repository ros-navigation/navigation2, pull requests merged in 2019-10, with the labels that each got.

#1172 Documentation Updates - Bringup, Nav 2 with Slam
  doc/use_cases/navigation_with_slam.md
  nav2_bringup/bringup/README.md
Labels: documentation, for review

#1095 Update BUILD.md
  doc/BUILD.md
Labels: 2 - Medium, documentation

#1230 New Navigation2 with Turtlebot 3 tutorial
  doc/tutorials/images/Navigation2_on_real_Turtlebot3/rviz_after_launch_view.png
  doc/tutorials/images/Navigation2_on_real_Turtlebot3/rviz_robot_navigating.png
  doc/tutorials/images/Navigation2_on_real_Turtlebot3/rviz_send_goal.png
  doc/tutorials/images/Navigation2_on_real_Turtlebot3/rviz_set_initial_pose.png
  doc/tutorials/images/Navigation2_on_real_Turtlebot3/rviz_slam_map_view.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/gazebo_robot_reached_goal.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/gazebo_turlebot3.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/navigation_with_recovery_behaviours.gif
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_initial_view.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_robot_navigating.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_send_goal_pose.png
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_set_goal_pose.png
  doc/tutorials/navigation2_on_real_turtlebot3.md
  doc/tutorials/navigation2_with_turtlebot3_in_gazebo.md
Labels: documentation

#1265 Updated tutorial image links
  doc/tutorials/images/Navigation2_with_Turtlebot3_in_Gazebo/rviz_set_initial_pose.png
  doc/tutorials/navigation2_on_real_turtlebot3.md
  doc/tutorials/navigation2_with_turtlebot3_in_gazebo.md
Labels: documentation
