Repository ros-navigation/navigation2, pull requests merged in 2019-06, with the labels that each got.

#794 Enable BaseObstacle critic and declare critic scale parameters
  nav2_bringup/launch/nav2_params.yaml
  nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp
Labels: 1 - High, nav2_lifecycle

#797 Remove apt key from Dockerfile
  Dockerfile
Labels: build

#796 Update costmap on new computePathToPose
  nav2_navfn_planner/src/navfn_planner.cpp
Labels: 1 - High, nav2_lifecycle

#804 Only allow one spin_until_future_complete at a time
  nav2_tasks/include/nav2_tasks/bt_action_node.hpp
Labels: nav2_lifecycle

#798 lifecycle branch - remove apt key from Dockerfile
  Dockerfile
Labels: build, nav2_lifecycle

#805 Re-enable costmap tests (footprint and inflation tests)
  nav2_costmap_2d/package.xml
  nav2_costmap_2d/src/costmap_2d_ros.cpp
  nav2_costmap_2d/src/layer.cpp
  nav2_costmap_2d/test/integration/CMakeLists.txt
  nav2_costmap_2d/test/integration/costmap_tests_launch.py
  nav2_costmap_2d/test/integration/footprint_tests.cpp
  nav2_costmap_2d/test/integration/inflation_tests.cpp
  nav2_costmap_2d/test/integration/obstacle_tests.cpp
  nav2_costmap_2d/test/integration/static_tests.cpp
Labels: nav2_lifecycle

#802 Enable navigation goal preemption
  nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
  nav2_tasks/include/nav2_tasks/bt_action_node.hpp
  nav2_tasks/src/behavior_tree_engine.cpp
  nav2_util/include/nav2_util/simple_action_server.hpp
Labels: 1 - High, nav2_lifecycle

#808 Spin the node from the blackboard before calling getCurrentPose
  nav2_tasks/include/nav2_tasks/goal_reached_condition.hpp
  nav2_tasks/include/nav2_tasks/is_localized_condition.hpp
Labels: nav2_lifecycle

#777 Add an all-in-one launch file for nav2 developers
  nav2_bringup/launch/nav2_simulation_launch.py
Labels: nav2_lifecycle

#809 Don't set the path_updated flag the first time through
  nav2_tasks/include/nav2_tasks/compute_path_to_pose_action.hpp
Labels: nav2_lifecycle

#810 Adding check for successful action cancellation after halting a bt action node
  nav2_tasks/include/nav2_tasks/bt_action_node.hpp
Labels: 1 - High, nav2_lifecycle

#795 Enable localization test
  nav2_system_tests/CMakeLists.txt
Labels: nav2_lifecycle

#843 Use_sim_time missing from a couple nodes in the params file
  nav2_bringup/launch/nav2_params.yaml
Labels: 0 - Critical

#839 Run lint tools on nav2_lifecycle_manager and nav2_tasks
  nav2_lifecycle_manager/src/lifecycle_manager.cpp
  nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
  nav2_tasks/include/nav2_tasks/bt_action_node.hpp
Labels: 1 - High

#831 update global plan and footprint topic names in rviz
  nav2_bringup/launch/nav2_default_view.rviz
Labels: 1 - High

#838 Delete pause/resume buttons and services
  nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
  nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager_client.hpp
  nav2_lifecycle_manager/src/lifecycle_manager.cpp
  nav2_lifecycle_manager/src/lifecycle_manager_client.cpp
  nav2_rviz_plugins/include/nav2_rviz_plugins/nav2_panel.hpp
  nav2_rviz_plugins/src/nav2_panel.cpp
Labels: 1 - High

#845 Call now on the main lifecycle nodes instead of rclcpp_nodes
  nav2_amcl/src/amcl_node.cpp
  nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
  nav2_costmap_2d/src/costmap_2d_ros.cpp
Labels: 2 - Medium

#836 Revert back to CoroActionNodes instead of AsyncActionNodes
  nav2_tasks/include/nav2_tasks/bt_action_node.hpp
Labels: 1 - High

#859 Consolidate related parameter sections under a single namespace heading
  nav2_bringup/launch/nav2_params.yaml
Labels: 0 - Critical

#863 Re-add republishing of map every 2 sec
  nav2_map_server/include/nav2_map_server/occ_grid_loader.hpp
  nav2_map_server/src/occ_grid_loader.cpp
Labels: 1 - High

#857 Adding RecoveryNode to Behavior Tree
  nav2_bt_navigator/CMakeLists.txt
  nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
  nav2_bt_navigator/include/nav2_bt_navigator/recovery_node.hpp
  nav2_bt_navigator/src/navigate_to_pose_behavior_tree.cpp
  nav2_bt_navigator/src/recovery_node.cpp
Labels: 2 - Medium

#869 Removed unnecessary info messages
  nav2_costmap_2d/plugins/static_layer.cpp
  nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_world_model/src/world_model.cpp
Labels: 2 - Medium

#719 Fix "no valid trajectories" when obstacle on path
  nav2_dwb_controller/dwb_critics/src/map_grid.cpp
Labels: 1 - High

#871 Catch polymorphic exceptions by reference
  nav2_amcl/src/amcl_node.cpp
  nav2_costmap_2d/plugins/static_layer.cpp
  nav2_map_server/src/map_server.cpp
  nav2_map_server/src/occ_grid_loader.cpp
Labels: 0 - Critical

#720 Add support for DWB to use a costmap in the base_link frame
  nav2_bringup/launch/nav2_params.yaml
  nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
  nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
  nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/tf_help.hpp
  nav2_system_tests/params/nav2_params.yaml
  nav2_system_tests/src/system/CMakeLists.txt
  nav2_system_tests/src/system/test_system_launch.py
  tools/run_test_suite.bash
Labels: 2 - Medium

#875 Improve shutdown reliability
  nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
  nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
  nav2_world_model/include/nav2_world_model/world_model.hpp
  nav2_world_model/src/world_model.cpp
Labels: 2 - Medium

#884 Reverse order of shutdown nodes
  nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
  nav2_lifecycle_manager/src/lifecycle_manager.cpp
Labels: 1 - High

#847 Amcl map update
  nav2_amcl/include/nav2_amcl/amcl_node.hpp
  nav2_amcl/src/amcl_node.cpp
Labels: 1 - High

#890 Fixed nav2_util uncrustify issue
  nav2_util/src/map/map_cspace.cpp
Labels: 0 - Critical

#606 Adding a docker file to help test for missing package.xml dependencies
  Dockerfile
  Dockerfile.full_ros_build
  Dockerfile.release_branch
  doc/process/PreReleaseChecklist.md
Labels: 1 - High

#880 Addressing bt_navigator crash
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_util/include/nav2_util/simple_action_server.hpp
Labels: 1 - High

#849 Extended the SimpleActionServer interface
  nav2_bt_navigator/include/nav2_bt_navigator/bt_navigator.hpp
  nav2_bt_navigator/src/bt_navigator.cpp
  nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp
  nav2_dwb_controller/dwb_controller/include/dwb_controller/progress_checker.hpp
  nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp
  nav2_motion_primitives/include/nav2_motion_primitives/motion_primitive.hpp
  nav2_motion_primitives/src/back_up.cpp
  nav2_motion_primitives/src/spin.cpp
  nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_tasks/include/nav2_tasks/behavior_tree_engine.hpp
  nav2_tasks/src/behavior_tree_engine.cpp
  nav2_util/include/nav2_util/simple_action_server.hpp
  nav2_util/src/lifecycle_node.cpp
  nav2_util/test/test_actions.cpp
Labels: 1 - High

#882 Update Bt navigator readme
  nav2_bt_navigator/README.md
  nav2_bt_navigator/doc/parallel.png
  nav2_bt_navigator/doc/parallel_w_recovery.png
  nav2_bt_navigator/doc/proposed_recovery.png
  nav2_bt_navigator/doc/recovery1.png
  nav2_bt_navigator/doc/recovery2.png
  nav2_bt_navigator/doc/recovery3.png
  nav2_bt_navigator/doc/recovery4.png
  nav2_bt_navigator/doc/recovery_node.png
  nav2_bt_navigator/doc/simple.png
  nav2_bt_navigator/doc/simple_parallel.png
Labels: 1 - High
