Repository ros-navigation/navigation2, pull requests merged in 2024-07, with the labels that each got.

#4518 Behavior tree node for extracting pose from path
  nav2_behavior_tree/CMakeLists.txt
  nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/get_pose_from_path_action.hpp
  nav2_behavior_tree/plugins/action/get_pose_from_path_action.cpp
  nav2_behavior_tree/test/plugins/action/CMakeLists.txt
  nav2_behavior_tree/test/plugins/action/test_get_pose_from_path_action.cpp
Labels: backport-humble, backport-iron, backport-jazzy

#4530 Fix dock orientation while moving backwards
  nav2_docking/opennav_docking/src/docking_server.cpp
Labels: backport-jazzy

#4527 Fix backward motion for graceful controller
  nav2_graceful_controller/include/nav2_graceful_controller/ego_polar_coords.hpp
  nav2_graceful_controller/include/nav2_graceful_controller/smooth_control_law.hpp
  nav2_graceful_controller/src/smooth_control_law.cpp
  nav2_graceful_controller/test/test_egopolar.cpp
Labels: backport-humble, backport-jazzy

#4574 Add mutex to reloadDbCb to fail if called during docking
  nav2_docking/opennav_docking/include/opennav_docking/dock_database.hpp
  nav2_docking/opennav_docking/include/opennav_docking/docking_server.hpp
  nav2_docking/opennav_docking/src/dock_database.cpp
  nav2_docking/opennav_docking/src/docking_server.cpp
Labels: backport-jazzy
