Repository ros-navigation/navigation2, pull requests merged in 2025-06, with the labels that each got.

#5187 Option to Reduce Lethal to High-Cost Navigable To Get Out of Keepout Zones if Wandered In
  nav2_bringup/params/nav2_params.yaml
  nav2_costmap_2d/include/nav2_costmap_2d/costmap_filters/keepout_filter.hpp
  nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp
Labels: backport-kilted

#5207 Prototype solving #5192 Issue 2: Reeds-Shepp reduce small reverse expansions
  nav2_bringup/launch/tb3_loopback_simulation_launch.py
  nav2_bringup/launch/tb3_simulation_launch.py
  nav2_smac_planner/include/nav2_smac_planner/analytic_expansion.hpp
  nav2_smac_planner/src/analytic_expansion.cpp
  nav2_smac_planner/test/test_a_star.cpp
Labels: backport-kilted

#5237 Revert "Fix Ci from key signing (#5220)"
  .circleci/config.yml
  Dockerfile
Labels: backport-humble, backport-jazzy, backport-kilted

#5278 Use fixed thresholds for Trinary yaml
  nav2_map_server/src/map_io.cpp
Labels: backport-humble-main, backport-kilted
