Repository ros-navigation/navigation2, pull requests merged in 2025-05, with the labels that each got.

#5134 Make sure fixed curvature lookahead distance doesn't overshoot distance to cusp with RPP controller
  nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
Labels: backport-jazzy

#5141 Fix lattice backward 180 deg issue
  nav2_smac_planner/src/node_lattice.cpp
Labels: backport-jazzy

#5140 Fix - #5094 rotation shim stateful goal checking
  nav2_controller/CMakeLists.txt
  nav2_controller/include/nav2_controller/plugins/position_goal_checker.hpp
  nav2_controller/plugins.xml
  nav2_controller/plugins/position_goal_checker.cpp
  nav2_rotation_shim_controller/CMakeLists.txt
  nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/nav2_rotation_shim_controller.hpp
  nav2_rotation_shim_controller/include/nav2_rotation_shim_controller/tools/utils.hpp
  nav2_rotation_shim_controller/package.xml
  nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
Labels: question

#5105 fix MPPI goal critic inversion (#5088)
  nav2_mppi_controller/README.md
  nav2_mppi_controller/include/nav2_mppi_controller/critics/cost_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/goal_angle_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/goal_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/obstacles_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/path_align_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/path_angle_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/path_follow_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/prefer_forward_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/critics/twirling_critic.hpp
  nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp
  nav2_mppi_controller/src/critics/cost_critic.cpp
  nav2_mppi_controller/src/critics/goal_angle_critic.cpp
  nav2_mppi_controller/src/critics/goal_critic.cpp
  nav2_mppi_controller/src/critics/obstacles_critic.cpp
  nav2_mppi_controller/src/critics/path_align_critic.cpp
  nav2_mppi_controller/src/critics/path_angle_critic.cpp
  nav2_mppi_controller/src/critics/path_follow_critic.cpp
  nav2_mppi_controller/src/critics/prefer_forward_critic.cpp
  nav2_mppi_controller/src/critics/twirling_critic.cpp
  nav2_mppi_controller/test/critics_tests.cpp
  nav2_mppi_controller/test/utils_test.cpp
Labels: backport-jazzy, kilted-release

#5106 Dynamic Parameters Only validating params that are part of the plugin
  nav2_amcl/src/amcl_node.cpp
  nav2_collision_monitor/src/polygon.cpp
  nav2_collision_monitor/src/source.cpp
  nav2_controller/plugins/pose_progress_checker.cpp
  nav2_controller/plugins/simple_goal_checker.cpp
  nav2_controller/plugins/simple_progress_checker.cpp
  nav2_controller/plugins/stopped_goal_checker.cpp
  nav2_controller/src/controller_server.cpp
  nav2_controller/test/test_dynamic_parameters.cpp
  nav2_costmap_2d/plugins/inflation_layer.cpp
  nav2_costmap_2d/plugins/obstacle_layer.cpp
  nav2_costmap_2d/plugins/plugin_container_layer.cpp
  nav2_costmap_2d/plugins/static_layer.cpp
  nav2_costmap_2d/plugins/voxel_layer.cpp
  nav2_costmap_2d/src/costmap_2d_ros.cpp
  nav2_docking/opennav_docking/src/controller.cpp
  nav2_docking/opennav_docking/src/docking_server.cpp
  nav2_docking/opennav_docking/test/test_docking_server_unit.cpp
  nav2_dwb_controller/dwb_plugins/src/kinematic_parameters.cpp
  nav2_graceful_controller/src/parameter_handler.cpp
  nav2_mppi_controller/benchmark/optimizer_benchmark.cpp
  nav2_mppi_controller/include/nav2_mppi_controller/tools/parameters_handler.hpp
  nav2_mppi_controller/src/controller.cpp
  nav2_mppi_controller/src/parameters_handler.cpp
  nav2_mppi_controller/test/critic_manager_test.cpp
  nav2_mppi_controller/test/critics_tests.cpp
  nav2_mppi_controller/test/motion_model_tests.cpp
  nav2_mppi_controller/test/noise_generator_test.cpp
  nav2_mppi_controller/test/optimizer_smoke_test.cpp
  nav2_mppi_controller/test/optimizer_unit_tests.cpp
  nav2_mppi_controller/test/parameter_handler_test.cpp
  nav2_mppi_controller/test/path_handler_test.cpp
  nav2_mppi_controller/test/trajectory_visualizer_tests.cpp
  nav2_navfn_planner/src/navfn_planner.cpp
  nav2_planner/src/planner_server.cpp
  nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp
  nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp
  nav2_smac_planner/src/smac_planner_2d.cpp
  nav2_smac_planner/src/smac_planner_hybrid.cpp
  nav2_smac_planner/src/smac_planner_lattice.cpp
  nav2_theta_star_planner/src/theta_star_planner.cpp
  nav2_velocity_smoother/src/velocity_smoother.cpp
  nav2_waypoint_follower/src/waypoint_follower.cpp
Labels: kilted-release
